### ISSUE TITLE
Feature Request: Reconnect after disconnect

### ISSUE THREAD

**Issue by kylhuk** [no-fee-ethereum-mining/nsfminer#56] opened 2021-02-03 22:44 UTC
**Is your feature request related to a problem? Please describe.**
Every day at 0400 AM I'm restarting all my network devices which results in a disconnect from the stratum server. Right now nsfminer just immediately cancels and does not have any grace period/timeout setting.

**Describe the solution you'd like**
A parameter where you can say how to handle a disconnect.
```
-r X	 If set, nsfminer will retry to connect every 60 seconds, with a maximum of X tries. Set to 0 for infinite tries
```

**Describe alternatives you've considered**
No alternatives consideret yet. Of course, with an external app I could check if the API is still available. For smaller miners not really an option.

**Comment by parasyte** [comment] 2021-02-04 03:37
Have you tried configuring `--work-timeout`? It defaults to 180 seconds.

There are other retry handling args available as well, see `--help-module misc`

**Comment by viniciusferrao** [comment] 2021-02-04 04:55
I was already working on this but the code is bugged due to some race condition. Since you've opened the issue I just opened a PR to see if anyone with better C++ skills than I could help.

The PR is available here: https://github.com/no-fee-ethereum-mining/nsfminer/pull/57

Your issue is the same that I'm trying to solve. I don't have a failover pool, so it's guaranteed that the miner will quit instead of just sleeping for a brief moment and them tries to reconnect in an eternal loop.

**Comment by xgnom666x** [comment] 2021-02-04 11:11
> I was already working on this but the code is bugged due to some race condition. Since you've opened the issue I just opened a PR to see if anyone with better C++ skills than I could help.
> 
> The PR is available here: #57
> 
> Your issue is the same that I'm trying to solve. I don't have a failover pool, so it's guaranteed that the miner will quit instead of just sleeping for a brief moment and them tries to reconnect in an eternal loop.

I think the problem is that authentication on the pool was not passed
In general, there is



> **Is your feature request related to a problem? Please describe.**
> Every day at 0400 AM I'm restarting all my network devices which results in a disconnect from the stratum server. Right now nsfminer just immediately cancels and does not have any grace period/timeout setting.
> 
> **Describe the solution you'd like**
> A parameter where you can say how to handle a disconnect.
> 
> ```
> -r X	 If set, nsfminer will retry to connect every 60 seconds, with a maximum of X tries. Set to 0 for infinite tries
> ```
> 
> **Describe alternatives you've considered**
> No alternatives consideret yet. Of course, with an external app I could check if the API is still available. For smaller miners not really an option.

--response-timeout (=sec)   If no response from pool to a stratum message after this amount of time the connection is dropped 
--retry-delay (=sec)      Delay in seconds before reconnection retry
--farm-retries arg (=sec)     Set number of reconnection retries to same pool

**Comment by kylhuk** [comment] 2021-02-04 11:40
@xgnom666x 
Thanks. So I tried those parameters. Only `--retry-delay` seems to work, the others are getting ignored.

@parasyte 
Tried `--work-timeout`, seems to have no effect.

How I tested it:
Just enter a random pool destination, which is not reachable. I used google.com. After 2 tries, the program exits.

**Comment by xgnom666x** [comment] 2021-02-04 11:46
@kylhuk 
These options will only work if a connection to the pool has already been established. 
PS.sorry for my english

**Comment by kylhuk** [comment] 2021-02-04 11:50
@xgnom666x 
Oh, you are absolutely right! So in that case there only needs to be a feature, where it will retry even there has been no connection established yet.

My goal is to automate everything so if I restart my jobs while there is no internet connection, it should retry anyways.

**Comment by xgnom666x** [comment] 2021-02-04 12:51
@kylhuk 
I think it's easier to configure something like a "watchdog" that checks if there is Internet access/process(miner) is running. and if problems are found, it restarts the miner. I think it's easier this way.

**Comment by jean-m-cyr** [comment] 2021-02-04 16:31
Great idea and worth considering. However, as @viniciusferrao  discovered, handling of connects and disconnects is complicated and rife with pitfalls. It took months to get it right in Ethmminer and I hesitate to touch it at this point.

**Comment by jean-m-cyr** [comment] 2021-02-14 17:43
Closing. It is called the 'no-stinkin-fee' miner after all!

**Closed by jean-m-cyr** 2021-02-14 17:43 UTC
Labels: enhancement
