### ISSUE TITLE
Hashrate drops to 0 when monitor is turned off

### ISSUE THREAD

**Issue by lulunaluna** [no-fee-ethereum-mining/nsfminer#20] opened 2021-01-24 19:06 UTC
**Describe the bug**
Whenever my monitor turns off or goes to sleep, my hashrate drops to 0 and stays there. Have not seen this behavior on other miners. 

**To Reproduce**
Monitor goes to sleep due to idle, or power off monitor

**Expected behavior**
Continue hashing, or to throw an error so that it could be handled (exit and restart). 

**Screenshots (Optional)**
![Error](https://user-images.githubusercontent.com/77936135/105640483-51554400-5e4c-11eb-82e2-0c0ec25135b5.PNG)

In this screenshot, the 0 hash rate started the moment I turned off my monitor. 

**Environment (please complete the following information):**
- Operating System: Windows 10
- Hardware [e.g. GTX 1070]: RTX 3090
- nsfminer Version [e.g. 0.14]: 1.2.3
- nsfminer options used: -R --HWMON 2 --exit

**Additional context**

Thanks for keeping this project alive! 

If this bug is not easily solvable, would it be possible to include an option to exit the miner if the hashrate stays at 0 (or below a specified threshold) or a specified period of time?

**Comment by lulunaluna** [comment] 2021-01-24 19:15
I forgot to mentioned - the hash rate stays at 0 even after the monitor is back on. Only solution is a forced-close.

**Comment by jean-m-cyr** [comment] 2021-01-25 08:01
Seems Windows is shutting down or resetting your GPUs before going dark. I don't use Windows. Not sure how to prevent this?

**Comment by efrasyad** [comment] 2021-01-25 22:27
I'm not sure if this is similar case, but in my case, I'm running headless so I set never turn off monitor but the hash rate stay zero randomly, first was after running nearly 24hrs, then after 6hrs.
But the miner keep running with 0 hashrate and I have to terminate with ctrl-c.

**Comment by jean-m-cyr** [comment] 2021-01-25 22:37
Likely due to an undetected race condition in the opencl code. In the mean time I've implemented hung GPU detection. You have a couple of options. Use the --exit option which will terminate the miner, or create a reboot script to do whatever you want. See -H reboot for details.

**Comment by efrasyad** [comment] 2021-01-25 23:07
I checked in 1.2.5 can't see reboot options

```
D:\Downloads\nsfminer_1.2.5-windows_10-cuda_11.2-opencl>nsfminer.exe -H reboot

Error: The --help-module parameter must be one of the following: con test misc env cl cu api
```

*Also, windows10 detected the 1.2.5 as malware/trojan

**Comment by amit-purkait** [comment] 2021-01-26 13:34
> 
> 
> I checked in 1.2.5 can't see reboot options
> 
> ```
> D:\Downloads\nsfminer_1.2.5-windows_10-cuda_11.2-opencl>nsfminer.exe -H reboot
> 
> Error: The --help-module parameter must be one of the following: con test misc env cl cu api
> ```
> 
> *Also, windows10 detected the 1.2.5 as malware/trojan

requires a newer release.

**Comment by efrasyad** [comment] 2021-01-26 18:57
> > I checked in 1.2.5 can't see reboot options
> > ```
> > D:\Downloads\nsfminer_1.2.5-windows_10-cuda_11.2-opencl>nsfminer.exe -H reboot
> > 
> > Error: The --help-module parameter must be one of the following: con test misc env cl cu api
> > ```
> > 
> > 
> > *Also, windows10 detected the 1.2.5 as malware/trojan
> 
> requires a newer release.

I'm using latest release 1.2.5

**Comment by amit-purkait** [comment] 2021-01-30 15:42
Wait for the next release. Or ask the dev for one. I have built mine from the sources locally.

**Comment by lulunaluna** [comment] 2021-02-01 19:23
Thank you for the updates! Restarting hung GPUs work great :)

**Closed** 2021-02-07 04:25 UTC
Labels: ???

**Comment by liaralabs** [comment] 2021-02-10 18:23
I don't know if you want a separate issue for this, but the implemented solution doesn't seem to work for me. I suppose my symptoms are a bit different though the trigger seems to be the same.

When my monitor turns off on the current version, I get a "GPU0 Hung, Reboot failed" message (I'm paraphrasing from memory). Weirdly, the miner continues hashing at full speed in my case; however it is no longer finding shares (I found no shares in 14 minutes so I don't think it's just bad luck). It's effectively dead even though it's working at full speed. I read the docs and found I needed to add my own reboot script. So I did that, then I tested the monitor power off again and this time the reboot worked; however, the child process failed to build a DAG because the miner process didn't actually die and was still reserving the VRAM for the already generated DAG. So once my screen powers off, I now have one dead instance of NSF running at full speed and a second instance of NSF running at 0 because it can't generate the DAG.

I can appreciate that you are primarily using this on Linux and that you're not sure where to look for problems with this; however, for me, it makes this miner not an option for me because as soon as I walk away from the computer the miner effectively crashes. If I can supply anything else that maybe helpful, please let me know.

FWIW I don't have this issue when using the parent project EthMiner.

**Comment by amit-purkait** [comment] 2021-02-10 20:22
I had the same problem as yours with nsfminer. There is no solution for this in latest release, but a workaround using the --exit option and/or writing your own reboot script with --reboot. With exit option the miner would close if hashrate goes 0 and you could force restarting the miner again in a loop. This is what I did in a small batch script:

`
for /L %%n in (1,1,100) do (
  nsfminer.exe -P stratum1+ssl://<your_wallet>.<worker_name>@<pool> -U -R  --exit
)
`

You are correct on ethminer not having the same bug as this miner, although this being forked from it. If you compiled your own nsfminer, then I would suggest you compile the latest source from ethminer project. They already have a solution for 30xx cards in the latest source. Compiling is almost similar to nsfminer.

**Comment by liaralabs** [comment] 2021-02-11 01:48
I already am using the git head for EthMiner which is how I was able to compare the software, but I just wanted to pass along that indeed the bug still persists and that the workaround has not worked for me. Perhaps the `--exit` and `--reboot` arguments would help, but I'm not sure -- my hash rate on the main thread stays around 60MH/s even after the GPU Halt, so I'm not sure if `--exit` would work as intended in that circumstance; however, nsf does indeed detect the GPU hang properly.

I am indeed sticking to EthMiner for now though I would generally prefer to use the software which is more actively maintained.
