### ISSUE TITLE
The cores of main display graphics card is halved in mining

### ISSUE THREAD

**Issue by InbornLee** [no-fee-ethereum-mining/nsfminer#163] opened 2021-03-27 15:29 UTC
I have a computer with a CPU AMD 3700x and a single RX6700XT graphics card connected to the monitor. The number of cores of the graphics card is 40cu. When using ethminer, it prompts "adjusting CL work multiplier for 20 cus. Adjusted work Multiplier: 36409", The hash rate of VRAM after overclocking is only 27mh/s. Using nsfminer does not prompt the number of core uses, but the hash rate of VRAM after overclocking is also only 27mh/s. When the second RX6700XT is added, the second graphics card can run at a full speed of 46mh/s. What's the reason? Driver problem? My system is Windows10 120.2212.551.0，graphics card driver version is 20.50.03.01-210310a-365057E-RadeonSoftwareAdrenalin2020

**Comment by lesjokolat** [comment] 2021-03-27 17:28
This looks to be related to this issue I have.

https://github.com/no-fee-ethereum-mining/nsfminer/issues/23

**Comment by jean-m-cyr** [comment] 2021-03-28 01:33
Duplicate of #23. Closing

**Closed by jean-m-cyr** 2021-03-28 01:33 UTC
